name: Build and Release
on:
  push:
    tags:
      - '*'

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
  GITHUB_CLIENT_ID: ${{ secrets.APP_GITHUB_CLIENT_ID }}
  APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
  APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
  APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get version from package.json
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        shell: bash

      - name: Check if tag matches package version
        # タグ名とPACKAGE_VERSIONが一致していないと、ここの step でエラーになるので
        # package.json の version とタグを一致させること
        run: |
          if [ "refs/tags/${{ env.PACKAGE_VERSION }}" != "${{ github.ref }}" ]; then
            echo "Tag does not match package version!"
            exit 1
          fi

      - name: Check environment exists
        env:
          MAC_CSC_LINK: ${{ secrets.MAC_CSC_LINK }}
          MAC_CSC_PASSWORD: ${{ secrets.MAC_CSC_PASSWORD }}
        run: |
          echo ${#GOOGLE_CLIENT_ID}
          echo ${#GITHUB_CLIENT_ID}
          echo ${#MAC_CSC_LINK}
          echo ${#MAC_CSC_PASSWORD}
        shell: bash

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.1
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: Release ${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false

  release:
    needs: create-release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-14, windows-latest, ubuntu-latest]
        node-version: [18.x]
        include:
          - os: macos-13
            platform: mac
            architecture: x64
            ext: dmg
          - os: macos-14
            platform: mac
            architecture: arm64
            ext: dmg
          - os: windows-latest
            platform: win
            architecture: x64
            ext: exe
          - os: ubuntu-latest
            platform: linux
            architecture: x64
            ext: AppImage

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # ネイティブモジュールの rebuild が実行されるときに、node_modules のディレクトリの
      # 削除に失敗して、よくエラーになる。
      # もしも、「Install dependencies」の step で、node_modules 配下のディレクトリ削除で
      # エラーになるときには、 UI から「Re-run jobs」してください。
      # 一回、うまくいったら、キャッシュしてくれるので、エラーが出なくなるのだけど、
      # package-lock.json を変更するコミットがあると、キャッシュがクリアされるので、
      # エラーが出ることがあると思われる。
      # また、キャッシュした内容がおかしくてエラーになることもあるので、
      # job をキャンセルしたときなど、キャッシュが中途半端になってると、ビルドがうまくいかないので、
      # 「※キャッシュの強制削除」のところを有効にして、実行してみてほしい。
      - name: Cache dependencies
        # 元々windows版のリリースにのみ書かれていた処理のため
        if: startsWith(matrix.os,'windows')
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            C:\Users\runneradmin\AppData\Local\npm-cache
          key: ${{ runner.os }}-node-${{ hashFiles('**\package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # ※キャッシュの強制削除
      # - name: Clear node_modules if exists
      #   if: startsWith(matrix.os,'windows')
      #   run: |
      #     if (Test-Path node_modules) {
      #       Remove-Item -Recurse -Force node_modules
      #     }
      #   shell: pwsh

      # - name: Clear npm cache
      #   run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: set CSC for Mac
        if: startsWith(matrix.os,'macos')
        env:
          MAC_CSC_LINK: ${{ secrets.MAC_CSC_LINK }}
          MAC_CSC_PASSWORD: ${{ secrets.MAC_CSC_PASSWORD }}
        run: |
          echo "CSC_LINK=${MAC_CSC_LINK}" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${MAC_CSC_PASSWORD}" >> $GITHUB_ENV
        shell: bash

      - name: set CSC for Windows
        if: startsWith(matrix.os,'windows')
        env:
          WINDOWS_CSC_LINK: ${{ secrets.WINDOWS_CSC_LINK }}
          WINDOWS_CSC_PASSWORD: ${{ secrets.WINDOWS_CSC_PASSWORD }}
        run: |
          echo "CSC_LINK=${WINDOWS_CSC_LINK}" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${WINDOWS_CSC_PASSWORD}" >> $GITHUB_ENV
        shell: bash

      - name: Build Electron App
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run build:${{ matrix.platform }}

      - name: Get version from package.json
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        shell: bash

      - name: check directory
        run: ls -R ./dist

      - name: Create GitHub Release and Upload Build
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./dist/minr-desktop-${{ env.PACKAGE_VERSION }}-${{ matrix.platform }}.${{ matrix.ext }}
          asset_name: minr-desktop-${{ env.PACKAGE_VERSION }}-${{ matrix.platform }}-${{ matrix.architecture }}.${{ matrix.ext }}
          asset_content_type: application/octet-stream
